# Generated by Django 4.1.1 on 2022-09-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Тип новости')),
                ('color', models.CharField(db_index=True, max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы новостей',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('shortDescription', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('fullDescription', models.TextField(blank=True, verbose_name='Описание')),
                ('newsType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colorNews.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
